Specification/SpecDemos/Web/Models/SmartPlaylist.cs
using Newtonsoft.Json;
using Web.Models.Specs;

namespace Web.Models
{
    public class SmartPlaylist
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public GlobalSongSpecification Specification { get; set; }

        [JsonIgnore]
        public string Json
        {
            get { return JsonConvert.SerializeObject(Specification); }
            set { Specification = JsonConvert.DeserializeObject<GlobalSongSpecification>(value); }
        }
    }
}

Specification/SpecDemos/Web/Models/Song.cs
using System;
using System.Collections.Generic;

namespace Web.Models
{
    public class Song
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public TimeSpan Length { get; set; }
        public int Year { get; set; }
        public int AlbumId { get; set; }
        public virtual Album Album { get; set; }
        public List<Genre> Genres { get; set; } = new List<Genre>();
        public int? Rating { get; set; }

        public bool IsPreferred()
        {
            return Rating.HasValue && Rating.Value >= 4;
        }

        public bool IsRecentFavorite()
        {
            if (DateTime.Now.Year - this.Year > 5) return false;

            return IsPreferred();
        }
    }
}

Specification/SpecDemos/Web/Controllers/Api/SongsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace Web.Controllers.Api
{
    public class SongsController : ApiController
    {
        // GET api/<controller>
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<controller>/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/<controller>
        public void Post([FromBody]string value)
        {
        }

        // PUT api/<controller>/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/<controller>/5
        public void Delete(int id)
        {
        }
    }
}

Specification/SpecDemos/Web/Controllers/SmartPlaylistsController.cs
using System.Linq;
using System.Web.Mvc;
using Web.Infrastructure;
using Web.Interfaces;
using Web.Models;
using Web.Models.Specs;

namespace Web.Controllers
{
    public class SmartPlaylistsController : Controller
    {
        private readonly SmartPlaylistRepository _smartPlaylistRepository;

        public SmartPlaylistsController(SmartPlaylistRepository smartPlaylistRepository)
        {
            _smartPlaylistRepository = smartPlaylistRepository;
        }

        public SmartPlaylistsController() : this(new SmartPlaylistRepository(new AppDbContext()))
        {
        }

        public ActionResult Index()
        {
            return View(_smartPlaylistRepository.List());
        }
    }
}

Specification/SpecDemos/Web/Controllers/SongsController.cs
using System.Linq;
using System.Web.Mvc;
using Web.Infrastructure;
using Web.Interfaces;
using Web.Models;
using Web.Models.Specs;

namespace Web.Controllers
{
    public class SongsController : Controller
    {
        private readonly ISongRepository _songRepository;

        public SongsController(ISongRepository songRepository)
        {
            _songRepository = songRepository;
        }

        public SongsController() : this(new SongRepository(new AppDbContext()))
        {
        }

        public ActionResult Index()
        {
            return View(_songRepository.List(new AllSongsSpecification()));
        }
        public ActionResult ByArtist(string artist)
        {
            ViewBag.Artist = artist;
            
            return View(_songRepository.List(new SongArtistSpecification(artist)));
        }
        public ActionResult ByAlbum(int albumId)
        {
            var songs = _songRepository.List(new SongAlbumSpecification(albumId));
            if (songs.Any())
            {
                ViewBag.Album = songs.FirstOrDefault().Album.Title;
            }
            return View(songs);
        }
        public ActionResult ByYear(int year)
        {
            ViewBag.Year = year;
            return View(_songRepository.List(new SongYearSpecification(year)));
        }
        public ActionResult MinRating(int rating)
        {
            ViewBag.MinRating = rating;
            return View(_songRepository.List(new SongRatingSpecification(rating)));
        }

        public ActionResult RecentFavorites()
        {
            return View(_songRepository.List(new AllSongsSpecification()).Where(s => s.IsRecentFavorite()));
        }

        public ActionResult ByPlaylist(string playlistName)
        {
            // TODO: Use DI
            var playlistRepo = new SmartPlaylistRepository(new AppDbContext());

            var playlist = playlistRepo.GetByName(playlistName);
            if (playlist == null)
            {
                return HttpNotFound("Playlist not found.");
            }
            ViewBag.PlaylistName = playlist.Name;
            return View(_songRepository.List(playlist.Specification));

        }
    }
}

Specification/SpecDemos/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("myTunes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Query", "Index", "Home")</li>
                    <li>@Html.ActionLink("All Songs", "Index", "Songs")</li>
                    <li>@Html.ActionLink("Recent Favorites", "RecentFavorites", "Songs")</li>
                    <li>@Html.ActionLink("Smart Playlists", "Index", "SmartPlaylists")</li>
                    <li>@Html.ActionLink("Reset Database", "ResetDatabase", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Specification/SpecDemos/Web/Views/Shared/_SmartPlaylists.cshtml
@model IEnumerable<Web.Models.SmartPlaylist>
<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(s => s.Name)</th>
        <th>@Html.DisplayNameFor(s => s.Json)</th>
    </tr>
    @foreach (var playlist in Model)
    {
        <tr>
            <td><a href="/Songs/ByPlaylist?playlistName=@playlist.Name">@Html.DisplayFor(s => playlist.Name)</a></td>
            <td>@playlist.Json</td>
        </tr>
    }
</table>

Specification/SpecDemos/Web/Views/Shared/_Songs.cshtml
@model IEnumerable<Web.Models.Song>
<table class="table table-striped">
    <tr>
        <th>@Html.DisplayNameFor(s => s.Artist)</th>
        <th>@Html.DisplayNameFor(s => s.Title)</th>
        <th>@Html.DisplayNameFor(s => s.Album)</th>
        <th>@Html.DisplayNameFor(s => s.Year)</th>
        <th>@Html.DisplayNameFor(s => s.Length)</th>
        <th>@Html.DisplayNameFor(s => s.Rating)</th>
        <th>@Html.DisplayNameFor(s => s.Genres)</th>
    </tr>
    @foreach (var song in Model)
    {
        <tr>
            <td><a href="/Songs/ByArtist?artist=@song.Artist">@Html.DisplayFor(s => song.Artist)</a></td>
            <td>@Html.DisplayFor(s => song.Title)</td>
            <td><a href="/Songs/ByAlbum?albumId=@song.AlbumId">@Html.DisplayFor(s => song.Album.Title)</a></td>
            <td><a href="/Songs/ByYear?year=@song.Year">@Html.DisplayFor(s => song.Year)</a></td>
            <td>@Html.DisplayFor(s => song.Length)</td>
            <td><a href="/Songs/MinRating?rating=@song.Rating">@Html.DisplayFor(s => song.Rating)</a></td>
            <td>@string.Join(",", song.Genres.Select(g => g.Name))</td>
        </tr>
    }
</table>